name: Deploy
on:
  workflow_dispatch:
jobs:
  setup:
    name: Deploy latest commit
    runs-on: ubuntu-latest
    steps:
    - name: show val
      run: |
        echo secrets.SSH_USERNAME
        echo secrets.QA_HOST
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.QA_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_SECRET }}
        script: whoami
